version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: knowledge_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/knowledge_api
    volumes:
      - .:/app
    command: sh -c "python init_db.py && python main.py"

volumes:
  postgres_data: